on:
  push:
    branches:
      - master

name: Shellcheck shell scripts

jobs:
  shellcheck:
    name: Shellcheck all the things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
